services:
  postgres:
    image: postgres:15-alpine
    container_name: nubo-postgres
    environment:
      POSTGRES_USER: nubo
      POSTGRES_PASSWORD: nubo123
      POSTGRES_DB: nubo_email
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./nubo-backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - nubo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nubo"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nubo-redis
    ports:
      - "6379:6379"
    networks:
      - nubo-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./nubo-backend
      dockerfile: Dockerfile
    container_name: nubo-backend
    environment:
      PORT: 5001
      DATABASE_URL: postgresql://nubo:nubo123@postgres:5432/nubo_email
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nubo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./nubo-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5001/api
    container_name: nubo-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nubo-network
    restart: unless-stopped

networks:
  nubo-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: